name: Build frontend

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
      BASE_URL: ${{ secrets.BASE_URL }}
      NEXT_PUBLIC_SITE_DESCRIPTION: ${{ secrets.NEXT_PUBLIC_SITE_DESCRIPTION }}
      NEXT_PUBLIC_SITE_NAME: ${{ secrets.NEXT_PUBLIC_SITE_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/setup-node@v6
    
    - name: Install dependencies
      run: |
        cd frontend && npm install

    - name: Install mihomo
      run: |
        version=$(curl -skL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -skLo mihomo.deb https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-$version.deb
        sudo dpkg -i mihomo.deb

    - name: Convert AD Rules into mrs
      run: |
        cd frontend && npm run convert:ads

    - name: Convert AI Rules into mrs
      run: |
        cd frontend && npm run convert:ais

    - name: Build frontend
      run: |
        cd frontend && npm run build
        
    - name: Commit and push to mihomo branch
      run: |
        CURRENT_TIME=$(date +"%Y-%m-%d %H:%M")
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        mkdir -p /tmp/mihomo-deploy
        cp -r frontend/out/* /tmp/mihomo-deploy/
        git checkout --orphan mihomo
        git rm -rf .
        rm -rf *
        cp -r /tmp/mihomo-deploy/* .
        git add .
        git commit -m "Auto Update $CURRENT_TIME"
        git push -f origin mihomo

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 2